library(shiny)
library(shinylogs)

LOG_FILE <- 'logs'

if (!dir.exists(LOG_FILE)) {
  dir.create(LOG_FILE)
}

# Create Shiny app ----
shinyApp(
  # Define GUI via index.html + bundle.js (generated by Svelte/Rollup) ----
  ui = htmlTemplate(
    "templates/index.html",
    # ...
  ),

  # Define server logic ----
  server = server <- function(input, output, session) {

    track_usage(storage_mode = store_json(path = "logs/"))

    # Return the components of the URL in a string:
    output$urlText <- renderText({
      paste0(
        "protocol: ", session$clientData$url_protocol, "\n",
        "hostname: ", session$clientData$url_hostname, "\n",
        "pathname: ", session$clientData$url_pathname, "\n",
        "port: ",     session$clientData$url_port,     "\n",
        "search: ",   session$clientData$url_search,   "\n",
        "token: ",   session$token,   "\n",
        "app-token: ",   session$options$appToken,   "\n",
        sep = ""
      )
    })

    # Parse the GET query string
    output$queryText <- renderText({
      query <- parseQueryString(session$clientData$url_search)

      # Return a string with key-value pairs
      paste(
        names(query),
        sapply(query, function(q) {
          if (grepl(",", q))
            unlist(strsplit(q, split=","))
          else q
        }), sep = "=", collapse=", ")
    })

  }
)
