---
title: "Real~Currents"
subtitles:
  - "IxD:"
  - "Web:"
  - "Viz:"
format:
  gfm:
    variant: +yaml_metadata_block
---

This site is about signs and symbols in motion; a showcase of experiments in Information Experience Design (IxD). It's purpose is to recognize and explore our need to turn what often appears to be a tsunami or avalanche of data (waves) into familiar and intuitive patterns (currents) which have direction, velocity and stability (or meta-stability).

In terms of information and insight (wisdom):

  - Is disruption a consequence or a cause of novel phenomena, or could it be both?
  - Is the final impact of a tsunami to wreak havoc and destruction, or could it be...
      - the first phase of an unfolding wave of chain reactions which simultaneously...
        - transform the previous landscape
        - and give birth to a new environment?

Our interests lean toward producing and promoting methods for tracing the potential path (locus) of these phenomena, from where they begin to where they may lead, with an emphasis on interpretability, reasonability and usability.
