---
title: "Working with GLSL Shaders"
author: John
date: '2020-04-01'
draft: false
categories:
  - GL
tags:
  - GL
  - SvelteJS
  - SvelteGL
  - WebGL
---

<div id="glsl-app" role="main" style="width: 100%; min-width: 800px; margin-left: -86px;">
&nbsp;
</div>

## Shaders

```{r setup, include=FALSE}
options(warn = -1)
working_dir <- getwd()
print(working_dir)
if (!require("knitr")) {
    install.packages("knitr")
    library("knitr")
}
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(echo = TRUE)

# Load reticulate package for running python
if (!require("png")) {
    install.packages("png")
}
library(png)
```

ESSL 3.00 provides two types of constants (*uniform* and *attribute*) and one type of variable (*varying*). The scope of a *uniform* (`uniform`) is global, available to all shaders in the program, while the scope of an *attribute* (`in`) is limited to the shader in which it is defined. The scope of a *varying* (`in` and `out`) bridges the shader in which it is defined and initialized with the shader in which it is received. There are multiple classes (*storage qualifiers*) available for uniforms, attributes and varyings, like:

    vec3
    vec4
    mat4


There are also multiple levels of precision:

    lowp
    mediump
    highp


I've had to [make some changes](https://github.com/sveltejs/gl/pull/28) to [`@sveltejs/gl`](https://github.com/Real-Currents/SvelteGL/tree/real/currents), in order to create custom shaders, beginning by adding a declaration to all shaders compiled by `Material.mjs`:

        const { program, uniforms, attributes } = compile(
			gl,
			'#version 300 es' + '\n\n' + scene.defines + defines + '\n\n' + vert_builtin + '\n\n' + vert,
			'#version 300 es' + '\n\n' + scene.defines + defines + '\n\n' + frag_builtin + '\n\n' + frag
		);

Updating the shader version to 3.00 also required all attributes and varyings in the existing shaders to be re-declared using the new syntax. For example, what used to say:

    attribute vec3 position;
    attribute vec3 normal;

... had to be changed to say:

    in vec3 position;
    in vec3 normal;

The final output varying in the fragment shader also had to be changed because the gl_FragColor builtin was no longer valid:

    out mediump vec4 fragColor;
    ...

    #elif defined(has_color)
	fragColor = vec4(color, 1.0);
	#endif

	#ifdef has_alpha
	fragColor.a *= alpha;
	#endif

	fragColor.rgb *= mix(AMBIENT_LIGHT, vec3(1.0, 1.0, 1.0), lighting);
	fragColor.rgb += spec_amount;

With these changes in place I can now use all the latest shader features within WebGL-powered <a href="https://github.com/Real-Currents/SveltR" target="_blank">SveltR</a> apps and pages.
